export type TypeStep = { size: string; lineHeight: string }

export const tokens = {
  spacingUnit: "0.25rem",
  breakpoint: {
    sm: "40rem",
    md: "48rem",
    lg: "64rem",
    xl: "80rem",
  },
  color: {
    paper: "#FAF9F6",
    panel: "#F1EFE9",
    ink: "#17130F",
    "ink-secondary": "#6A6259",
    hairline: "#DAD5CC",
    surface: "#FFFFFF",
    vermilion: "#C8401B",
    "vermilion-hover": "#A93314",
    "vermilion-soft": "#F8E4DD",
    jade: "#2E8A66",
    "jade-soft": "#E4F1EA",
    "jade-bright": "#4DB58A",
    night: "#17130F",
    "night-text": "#F2EFE9",
    "night-muted": "#A39D94",
    "night-code": "#221D18",
    amber: "#B7791F",
    "amber-soft": "#F8EDD8",
  },
  font: {
    display: '"ZCOOL XiaoWei", "Noto Serif SC", "Songti SC", serif',
    body: '"Noto Sans SC", "PingFang SC", "Hiragino Sans GB", system-ui, sans-serif',
    mono: '"IBM Plex Mono", "SF Mono", Menlo, monospace',
  },
  text: {
    "label-2xs": { size: "10px", lineHeight: "1" },
    "label-xs": { size: "11px", lineHeight: "1.4" },
    "label-sm": { size: "12px", lineHeight: "1.5" },
    label: { size: "13px", lineHeight: "1.6" },
    code: { size: "13.5px", lineHeight: "1.75" },
    ui: { size: "14px", lineHeight: "1.5" },
    body: { size: "15px", lineHeight: "1.7" },
    "ui-lg": { size: "16px", lineHeight: "1.5" },
    "body-lg": { size: "17px", lineHeight: "1.7" },
    lede: { size: "18px", lineHeight: "1.7" },
    "brand-mark": { size: "19px", lineHeight: "1" },
    "heading-sm": { size: "20px", lineHeight: "1.4" },
    otp: { size: "22px", lineHeight: "1" },
    heading: { size: "24px", lineHeight: "1.35" },
    "heading-lg": { size: "26px", lineHeight: "1.3" },
    "display-sm": { size: "32px", lineHeight: "1.2" },
    "display-mobile": { size: "38px", lineHeight: "1.2" },
    "display-md": { size: "40px", lineHeight: "1.2" },
    "display-lg": { size: "44px", lineHeight: "1.15" },
    "display-xl": { size: "52px", lineHeight: "1.15" },
    "display-hero": { size: "64px", lineHeight: "1.15" },
  } satisfies Record<string, TypeStep>,
  fontWeight: {
    regular: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
  },
  tracking: {
    normal: "0",
    tight: "-0.01em",
    badge: "0.1em",
    eyebrow: "0.14em",
  },
  leading: {
    none: "1",
    tight: "1.15",
    snug: "1.2",
    heading: "1.3",
    normal: "1.5",
    relaxed: "1.6",
    prose: "1.7",
    code: "1.75",
  },
  radius: {
    "mark-sm": "3px",
    bar: "3px",
    mark: "4px",
    control: "6px",
    tile: "8px",
    card: "10px",
    sheet: "12px",
    pill: "999px",
  },
  container: {
    sidebar: "220px",
    aside: "400px",
    card: "440px",
    "lede-sm": "640px",
    lede: "680px",
    prose: "880px",
    board: "1040px",
    page: "1200px",
  },
  controlHeight: {
    "control-xs": "36px",
    "control-sm": "40px",
    control: "44px",
    "control-md": "46px",
    "control-lg": "48px",
    "control-xl": "56px",
  },
  borderWidth: {
    thin: "1px",
    frame: "1.5px",
    rule: "2px",
  },
  shadow: {
    menu: "0 12px 32px rgb(23 19 15 / 0.14)",
    focus: "0 0 0 3px rgb(200 64 27 / 0.25)",
  },
  opacity: {
    faint: "0.35",
    disabled: "0.5",
    muted: "0.6",
  },
  zIndex: {
    header: "10",
    menu: "20",
    overlay: "30",
  },
  duration: {
    fast: "120ms",
    base: "180ms",
    slow: "320ms",
    pulse: "1600ms",
  },
  ease: {
    standard: "cubic-bezier(0.2, 0, 0, 1)",
    pulse: "cubic-bezier(0.4, 0, 0.6, 1)",
  },
} as const

export type Tokens = typeof tokens
